# Generated by Django 4.2.30 on 2026-07-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_collaborator', '0001_initial'),
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecollaborator',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_collaborators', to='user.collaborator'),
        ),
        migrations.AddField(
            model_name='coursecollaborator',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_collaborators', to='course.course'),
        ),
        migrations.AddConstraint(
            model_name='coursecollaborator',
            constraint=models.UniqueConstraint(fields=('course', 'collaborator'), name='unique_course_collaborator'),
        ),
    ]
